#Lonelydesktop Colour Scheme
#By Midnight Salmon
#https://midnightsalmon.boo

[colors.primary]
background = "#1B1B1B"
foreground = "#BDBDBD"

[colors.normal]
black	= "#1B1B1B"
blue	= "#00567B"
green	= "#5E9D7C"
cyan	= "#4793A8"
red	= "#B75C61"
magenta	= "#71688A"
yellow	= "#A37D66"
white	= "#BDBDBD"

[colors.bright]
black	= "#797878"
blue	= "#5487C4"
green	= "#A3E6C7"
cyan	= "#95D6E0"
red	= "#EF9E9E"
magenta	= "#BABAFF"
yellow	= "#EEAA71"
white	= "#FFFFFF"
