#Lonelydesktop Colour Scheme
#By Midnight Salmon
#https://midnightsalmon.boo

[colors.primary]
background = "#34444D"
foreground = "#BDBDBD"

[colors.normal]
black	= "#1B1B1B"
red	= "#B75C61"
green	= "#5E9D7C"
yellow	= "#A37D66"
blue	= "#5486C4"
magenta	= "#8282AD"
cyan	= "#4793A8"
white	= "#BDBDBD"

[colors.bright]
black	= "#797878"
red	= "#EF9E9E"
green	= "#A3E6C7"
yellow	= "#EEAA71"
blue	= "#85C5ED"
magenta	= "#BABAFF"
cyan	= "#95D6E0"
white	= "#FFFFFF"
